### ISSUE TITLE
In case you haven't seen this...

### ISSUE THREAD

**Issue by akhra** [palf/haskellSDL2Examples#1]
http://keera.co.uk/blog/2014/10/15/from-60-fps-to-500/

Dunno if there's anything fresh for you there, but it's always worth peeking at other peoples' notes!

**Comment by DylanSale** [comment]
Cool but the android one still rendering at 15fps was worrying. I would
expect a game like that to run at at least 30fps on pretty much anything.

Dylan Sale

**Comment by akhra** [comment]
True, but note that Android _started_ at 10fps worst-case, meaning it's now rendering 1.5x and calculating at 3x the original code in the best-case comparison, compared to pushing 10x on PC. There's got to be some other platform-specific bottleneck they haven't yet found because all their profiling was done on PC.

**Comment by palf** [comment]
Thanks for the heads up on this! I'll try and run these examples on Android over the weekend, let you know what performance is like. I expect it'll tank. I've been learning from the same resources (Real World Haskell mostly) so there should be some overlap between these projects.
