### ISSUE TITLE
Consider working with Haskell SDL2 team?

### ISSUE THREAD

**Issue by akhra** [palf/haskellSDL2Examples#2]
https://github.com/haskell-game/sdl2 (new-api branch) is the repository slated to become `sdl2-2.0.0` on Hackage, and I believe they're done with breaking changes to the existing API.

They're also providing an implementation of this same example set. Any chance of teaming up?

**Comment by palf** [comment]
Hi @tejon, I should have thanked you for bringing this up ages ago. Unfortunately I wasn't able to make time to collaborate. I appreciate the consideration!

**Comment by akhra** [comment]
No worries, man... been there plenty of times myself.
