### ISSUE TITLE
cabal run lesson01 fails

### ISSUE THREAD

**Issue by michal-cab** [palf/haskellSDL2Examples#3]
hello and sorry for n00b question,
i followed you instructions and everything went well till <pre>cabal run lesson01 -v </pre> it spills out following:

---

<pre>
Using a sandbox located at ~/source/haskell2sdl/sandbox
Reading available packages...
Reading installed packages...
/opt/ghc/7.10.3/bin/ghc-pkg dump '--package-db=~/source/haskell2sdl/sandbox/i386-linux-ghc-7.10.2.20151102-packages.conf.d' -v0
/opt/ghc/7.10.3/bin/ghc --print-libdir
List of package sources written to file 'cabal-sdist-list-sources'
List of package sources written to file 'cabal-sdist-list-sources'
Found no modified add-source deps.
Component build order: executable 'lesson01'
creating dist/build
creating dist/build/autogen
/opt/ghc/7.10.3/bin/ghc-pkg init dist/package.conf.inplace
Preprocessing executable 'lesson01' for sdl2examples-0.1.0.0...
Building executable lesson01...
creating dist/build/lesson01
creating dist/build/lesson01/lesson01-tmp
/opt/ghc/7.10.3/bin/ghc --make -no-link -fbuilding-cabal-package -O -j2 -static -outputdir 
dist/build/lesson01/lesson01-tmp -odir dist/build/lesson01/lesson01-tmp -hidir dist/build/lesson01
/lesson01-tmp -stubdir dist/build/lesson01/lesson01-tmp -i -idist/build/lesson01/lesson01-tmp 
-isrc -idist/build/autogen -Idist/build/autogen -Idist/build/lesson01/lesson01-tmp -optP-include
 -optPdist/build/autogen/cabal_macros.h -hide-all-packages -no-user-package-db -package-db
 ~/source/haskell2sdl/sandbox/i386-linux-ghc-7.10.2.20151102-packages.conf.d -package-db
 dist/package.conf.inplace -package-id base-4.8.2.0-cda305297afd0b01a03f105bbbfa7122 
-package-id sdl2-1.3.0-191f406a500006baf3efde5321591f62 -XHaskell2010 src/lesson01.hs -Wall

src/lesson01.hs:4:8:
    Could not find module ‘Shared.Lifecycle’
    Use -v to see a list of the files searched for.

src/lesson01.hs:5:8:
    Could not find module ‘Shared.Utilities’
    Use -v to see a list of the files searched for.
 </pre>

---

i am@ubuntu 14.04 with ghc 7.10.2.20151102, cabal 1.22.4.0. 
so i know there is that src/shared dir with lifecycle.hs and utilities.hs i just dont know what to do to be found during compiling process. should i add something into sdl2_examples.cabal file? thnx for help...

**Comment by palf** [comment]
Hmm, I can't reproduce this on my Mac with a fresh sandbox. I'll set up an Ubuntu VM and try on there.
