### ISSUE TITLE
Not in scope: ‘SDLImage.withImgInit’ on Lesson06

### ISSUE THREAD

**Issue by babelchips** [palf/haskellSDL2Examples#6]
I'm receiving the following error when building and running lesson06 on Mac OS X 10.11.4.

```
cabal run lesson06
Preprocessing executable 'lesson06' for sdl2examples-0.1.0.0...
[8 of 8] Compiling Main             ( src/lesson06.hs, dist/build/lesson06/lesson06-tmp/Main.o )

src/lesson06.hs:27:29: Not in scope: ‘Image.withImgInit’
```

Lessons 1-5 work perfectly.  I understand this may just be a problem with the SDL or SDL-Image dependencies but I'm not sure what could be wrong.  The SDL C libraries were installed with Brew.  The cabal packages installed using the setup instructions in the Readme.md.  Any ideas?

**Comment by palf** [comment]
it looks like you're missing the sdl2-image haskell package, but that's covered in the README. Maybe the code is just wrong! I'd recommend looking at the updated examples in the hs sdl2 project instead (https://github.com/haskell-game/sdl2/blob/master/examples/lazyfoo/Lesson07.hs) - they don't have lesson06, but there should be enough to draw an example from
