### ISSUE TITLE
Module ‘Graphics.UI.SDL’ does not export  ....

### ISSUE THREAD

**Issue by kai-wang** [palf/haskellSDL2Examples#7]
Hello,

I am getting below issues when running "cabal run lessonxx". 

{23:35}[1.9.2]~/Workspace/haskell/sdl2-example:master ✗ ➭ cabal run lesson01
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring sdl2examples-0.1.0.0...
Preprocessing executable 'lesson01' for sdl2examples-0.1.0.0...
[1 of 3] Compiling Shared.Utilities ( src/Shared/Utilities.hs, dist/build/lesson01/lesson01-tmp/Shared/Utilities.o )
[2 of 3] Compiling Shared.Lifecycle ( src/Shared/Lifecycle.hs, dist/build/lesson01/lesson01-tmp/Shared/Lifecycle.o )

src/Shared/Lifecycle.hs:27:20: error:
    Not in scope: data constructor ‘SDL.SDL_INIT_VIDEO’
    Module ‘Graphics.UI.SDL’ does not export ‘SDL_INIT_VIDEO’.

src/Shared/Lifecycle.hs:39:39: error:
    Not in scope: data constructor ‘SDL.SDL_WINDOWPOS_UNDEFINED’
    Module ‘Graphics.UI.SDL’ does not export ‘SDL_WINDOWPOS_UNDEFINED’.

src/Shared/Lifecycle.hs:39:67: error:
    Not in scope: data constructor ‘SDL.SDL_WINDOWPOS_UNDEFINED’
    Module ‘Graphics.UI.SDL’ does not export ‘SDL_WINDOWPOS_UNDEFINED’.

src/Shared/Lifecycle.hs:39:99: error:
    Not in scope: data constructor ‘SDL.SDL_WINDOW_SHOWN’
    Module ‘Graphics.UI.SDL’ does not export ‘SDL_WINDOW_SHOWN’.

src/Shared/Lifecycle.hs:45:45: error:
    Not in scope: data constructor ‘SDL.SDL_RENDERER_ACCELERATED’
    Module ‘Graphics.UI.SDL’ does not export ‘SDL_RENDERER_ACCELERATED’.

**Comment by palf** [comment]
This is caused by having a newer version of the haskell SDL2 lib than the examples were written against. Try again, now that we've migrated to stack
